//! `/setup-github-actions` — write a starter `.github/workflows/jfc-review.yml`
//! template into the current repo.
//!
//! Mirrors v2.1.132's `tengu_setup_github_actions_*` flow. The bundled
//! workflow listens on `pull_request` + `pull_request_review_comment` and
//! invokes `claude-code-action` (the official Anthropic action) to either
//! review or auto-fix based on a `/claude` mention in the comment body.
//!
//! We intentionally don't write the secret — the user has to add
//! `ANTHROPIC_API_KEY` (or the Bedrock equivalents) in the repo's settings
//! after running the command. The post-write message guides them.

use std::path::{Path, PathBuf};

/// Default workflow filename. Matches v2.1.132's convention so a user moving
/// between Claude Code and jfc finds the same file.
pub const DEFAULT_WORKFLOW_PATH: &str = ".github/workflows/jfc-review.yml";

/// The starter workflow template. Pinned to the current `claude-code-action`
/// release tag to avoid surprise regressions.
pub const WORKFLOW_TEMPLATE: &str = r#"# Auto-generated by jfc `/setup-github-actions`.
# After this lands in main, add the ANTHROPIC_API_KEY secret in
#   Settings → Secrets and variables → Actions → New repository secret.
# Then comment "/claude review" on a PR to trigger a review run.
name: jfc-review

on:
  pull_request:
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created]
  pull_request_review:
    types: [submitted]
  pull_request_review_comment:
    types: [created]

jobs:
  claude-review:
    if: |
      (github.event_name == 'pull_request') ||
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '/claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '/claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '/claude'))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
      id-token: write
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 1
      - uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          # Tell the action which trigger phrase to listen for in comments.
          trigger_phrase: "/claude"
"#;

/// Result of a write attempt — distinguishes the "already exists" case so
/// the caller can show a different message.
#[derive(Debug)]
pub enum SetupOutcome {
    /// Workflow file written for the first time.
    Created(PathBuf),
    /// Workflow file already existed; we left it alone.
    AlreadyPresent(PathBuf),
    /// Forced overwrite of an existing file (only when `force=true`).
    Overwrote(PathBuf),
}

/// Write the workflow into `repo_root/.github/workflows/jfc-review.yml`.
///
/// `force=true` overwrites any existing file. When `force=false` we leave
/// existing files alone — this keeps the command idempotent for users who
/// have already customized the workflow.
pub fn write_workflow(repo_root: &Path, force: bool) -> std::io::Result<SetupOutcome> {
    let dest = repo_root.join(DEFAULT_WORKFLOW_PATH);
    if dest.exists() && !force {
        return Ok(SetupOutcome::AlreadyPresent(dest));
    }
    if let Some(parent) = dest.parent() {
        std::fs::create_dir_all(parent)?;
    }
    let pre_existed = dest.exists();
    std::fs::write(&dest, WORKFLOW_TEMPLATE)?;
    Ok(if pre_existed {
        SetupOutcome::Overwrote(dest)
    } else {
        SetupOutcome::Created(dest)
    })
}

/// Markdown blob shown in the chat after a successful write.
pub fn success_message(outcome: &SetupOutcome) -> String {
    let (verb, path) = match outcome {
        SetupOutcome::Created(p) => ("Created", p),
        SetupOutcome::AlreadyPresent(p) => {
            return format!(
                "Workflow already present at `{}`. Run `/setup-github-actions force` to overwrite.",
                p.display()
            );
        }
        SetupOutcome::Overwrote(p) => ("Overwrote", p),
    };
    format!(
        "{verb} **{path}**.\n\n\
         Next steps:\n\
         1. `git add {path}` and commit/push.\n\
         2. In GitHub: Settings → Secrets → Actions, add `ANTHROPIC_API_KEY`.\n\
         3. Open a PR and comment `/claude review` to trigger the action.",
        verb = verb,
        path = path.display()
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn write_workflow_creates_file_normal() {
        let dir = tempfile::tempdir().unwrap();
        let outcome = write_workflow(dir.path(), false).expect("write");
        match outcome {
            SetupOutcome::Created(p) => {
                assert!(p.ends_with(DEFAULT_WORKFLOW_PATH));
                let body = std::fs::read_to_string(&p).unwrap();
                assert!(body.contains("anthropics/claude-code-action"));
                assert!(body.contains("trigger_phrase: \"/claude\""));
            }
            other => panic!("expected Created, got {other:?}"),
        }
    }

    #[test]
    fn write_workflow_idempotent_without_force_robust() {
        let dir = tempfile::tempdir().unwrap();
        let _ = write_workflow(dir.path(), false).expect("first");
        let second = write_workflow(dir.path(), false).expect("second");
        assert!(matches!(second, SetupOutcome::AlreadyPresent(_)));
    }

    #[test]
    fn write_workflow_overwrites_with_force_normal() {
        let dir = tempfile::tempdir().unwrap();
        let _ = write_workflow(dir.path(), false).expect("first");
        let dest = dir.path().join(DEFAULT_WORKFLOW_PATH);
        std::fs::write(&dest, "# user customization").unwrap();
        let second = write_workflow(dir.path(), true).expect("forced");
        assert!(matches!(second, SetupOutcome::Overwrote(_)));
        let body = std::fs::read_to_string(&dest).unwrap();
        assert!(body.contains("anthropics/claude-code-action"));
    }

    #[test]
    fn success_message_for_already_present_robust() {
        let p = std::path::PathBuf::from(".github/workflows/jfc-review.yml");
        let msg = success_message(&SetupOutcome::AlreadyPresent(p));
        assert!(msg.contains("already present"));
        assert!(msg.contains("force"));
    }

    #[test]
    fn success_message_for_created_includes_next_steps_normal() {
        let p = std::path::PathBuf::from("/tmp/jfc-review.yml");
        let msg = success_message(&SetupOutcome::Created(p));
        assert!(msg.contains("Created"));
        assert!(msg.contains("ANTHROPIC_API_KEY"));
        assert!(msg.contains("/claude review"));
    }
}
